import type { AppLocale } from '../../shared/i18n';
import { deviceDefaultLocale, useLocaleOptional } from '../i18n/LocaleContext';

export const GOLD_ROOM_COPY = {
  he: {
    entryLabel: '🪙 חדר הזהב',
    entryA11y: 'פתח את חדר הזהב',
    roomName: 'חדר הזהב',
    roomTitle: 'חדר הזהב 🪙',
    chooseTask: 'בחר משימת אימון · הושלמו {{doneCount}}/{{totalUnlocked}}',
    exit: 'יציאה',
    backToRoom: 'חזרה לחדר הזהב',
    skip: 'דלג ›',
    back: '‹ חזור',
    backPlain: 'חזור',
    backShort: '‹ חזרה',
    continue: 'המשך ›',
    gotIt: 'הבנתי, בוא נתקדם!',
    close: 'סגור',
    start: 'התחל ›',
    completed: 'הושלם ✓',
    comingSoon: '🔒 בקרוב',
    collected: 'נאסף ✓',
    collect: 'אסוף ›',
    finishLearning: '🔒 סיים ללמוד',
    collectedA11y: ' (נאסף)',
    collectAvailableA11y: ' (זמין לאיסוף)',
    finishLearningA11y: ' (נעול — סיים את הלמידה)',
    completedA11y: ' (הושלם)',
    comingSoonA11y: ' (בקרוב)',
    basicsTitle: 'היסודות',
    basicsDesc: 'הערימה, המניפה והקוביות — תוך דקה.',
    basicsPracticeTitle: 'היסודות והתרגול',
    basicsPracticeDesc: 'מכירים את המסך וממשיכים מיד לבניית תרגיל ראשון.',
    practiceTitle: 'תרגול',
    practiceDesc: 'בחר קלף, הטל קוביות, ובנה משוואה.',
    specialsTitle: 'מיוחדים',
    specialsSteps: ['קלפי הסימן + / -', 'קלף סלינדה — אופרטור פראי', 'קלף הפרא — כל מספר', 'פינאלה וניצחון'],
    fractionsTitle: 'שברים',
    fractionsDesc: 'איך משחקים עם קלפי שברים.',
    salindasTitle: 'קלפי סלינדה',
    salindasDesc: 'אופרטור פראי שמכיל את כל הסימנים.',
    coinsTitle: 'מטבעות',
    coinsDesc: 'סיים את הלמידה ואסוף את המענק.',
    welcomeTitle: 'ברוך הבא! 🪙',
    welcomeBody: 'נכיר במהירות את המסך — שלושה חלקים בלבד, ואז יוצאים לשחק.',
    deckTag: 'הערימה',
    deckTitle: 'הערימה 🂠',
    deckBody: 'הערימה — בנק הקלפים, כאן למעלה בפינה.',
    fanBody: 'המניפה. זאת מניפת הקלפים שלך. החליקו לצדדים כדי לעבור בין הקלפים ולבחור קלף שמתאים לתרגיל.',
    victoryBody: 'הניצחון. מתחילים עם 7 קלפים, ומנצחים כשנשארים עם 2 קלפים או פחות. בכל תרגיל נכון תיפטרו מקלף ותתקרבו לניצחון.',
    diceBody: 'בכל תור, שלוש קוביות שיוטלו על הלוח ויקבעו את גורל הסיבוב. מהמספרים שיעלו תרכיבו את התרגילים שבעזרתם תיפטרו מקלפי המניפה שלכם.',
    rewardTitle: 'כל הכבוד!',
    rewardSub: 'קיבלת {{reward}} מטבעות על סיום הלמידה.',
    awesome: 'מעולה!',
    errorTitle: 'אופס…',
    errorSub: 'לא הצלחנו לזכות אותך כרגע. נסה שוב בעוד רגע.',
    tryAgain: 'נסה שוב',
    add: 'הוסף {{value}}',
    addDie: 'הוסף קובייה {{value}}',
    removeDie: 'הסר קובייה {{value}}',
    check: 'בדוק',
    checkMark: 'בדוק ✓',
    chooseCards: 'בחר קלפים',
    launch: 'שגר',
    finish: 'סיום',
    placePlusCard: 'מקם קלף פלוס בחריץ הסימן',
    placeSignCard: 'מקם קלף סימן בחריץ הריק',
    changeAction: 'החלף פעולה',
    checkEquation: 'בדוק את המשוואה',
    practicePlus: 'הביטו בקוביות ובמניפה. הרכבנו עבורכם תרגיל חיבור (+) שמגיע בדיוק ל-6. עכשיו, מצאו ולחצו על קלף 6 במניפה שלכם כדי לבחור אותו!',
    practiceMinus: 'עבודה מעולה! עכשיו האתגר גדל ועוברים לחיסור (-). הרכבנו עבורכם תרגיל חיסור (5 - 2) שמגיע בדיוק ל-3. מצאו ולחצו על קלף 3 במניפה שלכם!',
    firstCardLaunch: "מעולה! עכשיו לחצו על כפתור 'שגר' כדי להעיף את הקלף הראשון!",
    cardLaunch: "מצוין! לחצו על כפתור 'שגר' כדי להעיף את הקלף!",
    twoDiceHint: 'שתי קוביות מספיקות — קובייה שלישית היא רשות, לא חובה.',
    successSub: 'בנית תרגיל מהקוביות ונפטרת מהקלף המתאים ✓',
    salindaIntro: 'נתקעתם בלי הסימן המתאים? הכירו את קלף סלינדה! הקלף החזק ביותר במשחק שמכיל את כל הסימנים יחד.',
    salindaSelected: "מבריק! קלף סלינדה נטען בסימן הנכון והשלים את התרגיל. לחצו על כפתור 'שגר' כדי לנצח את חדר הזהב!",
    salindaPractice: 'בואו ננסה! לחצו על קלף סלינדה במניפה, בחרו סימן, והשחילו אותו למשוואה.',
    salindaOperatorIntro: 'נתקעתם בלי הסימן המתאים? הכירו את קלף סלינדה! הקלף החזק ביותר במשחק שמכיל את כל הסימנים יחד. לחצו עליו במניפה!',
    salindaSelectorTitle: 'בחרו סימן',
    salindaSelectorBody: 'בחרו את הסימן שאתם צריכים כדי לפתור את התרגיל (5 פחות 2 שווה 3)!',
    chooseOperatorA11y: 'בחר סימן {{op}}',
    salindaMinusLoaded: 'מעולה! עכשיו לחצו על חריץ הסימן הריק במשוואה כדי למקם את קלף סלינדה כמינוס!',
    salindaOperatorReady: "התרגיל מושלם! לחצו על קלף 3 במניפה ואז על 'שגר' כדי לנצח את חדר הזהב!",
    operatorReady: "התרגיל מושלם! לחצו על קלף 7 במניפה ואז על 'שגר' כדי להעיף אותו!",
    minusSlotReady: 'מצוין! עכשיו לחצו על חריץ הסימן הריק שבמשוואה למעלה.',
    minusIntro: 'כאן מחכה תרגיל של 5 ו-2 ששווה ל-7. לחצו על קלף החיבור (+) במניפה!',
    buildTarget: 'בנו משוואה שמגיעה ליעד',
    salindaTurn: 'תורו של קלף סלינדה',
    salindaActive: '👑 קלף סלינדה פעיל',
    // ── Specials sequence — opening showcase + three continuous on-board substeps ──
    signCardsShowcase: 'הכירו את קלפי הסימן: חיבור (+), חיסור (−), כפל (×) וחילוק (÷). הציבו אותם בתרגיל וכך תיפטרו מהם!',
    specialsLetsPractice: 'בוא נתרגל!',
    signCardsIntro: 'הכירו את קלפי הסימן + / -. הציבו אותם בתרגיל וכך תיפטרו מהם',
    salindaSeqIntro: 'הכירו את קלף סלינדה. הוא מכיל את כל הסימנים יחד! בחרו סימן, הציבו בתרגיל וכך תיפטרו מהקלף.',
    salindaSeqSelectorBody: 'בחרו את הסימן שיפתור את התרגיל 5 - 2 = 3.',
    salindaSeqReady: "מבריק! לחצו על קלף 3 במניפה ואז על 'שגר' כדי להעיף אותו!",
    wildIntro: 'תרגול קלף הפרא: לחצו על קלף הפרא במניפה כדי להשלים את התוצאה החסרה במשוואה.',
    wildReady: "הקלף הפך ל-8 והשלים את התרגיל. לחצו על כפתור 'שגר' כדי לנצח!",
    // ── Fraction cards training — attack (part A) + defense (part B) ──
    fractionAttackIntro: 'הכירו את קלפי השבר! זרקו את קלף השבר {{fraction}} על ה-{{number}} שבערימה כדי להיפטר ממנו ולהתקיף את השחקן הבא!',
    fractionDefenseIntro: 'אותגרתם! פתרון ראשון: הציבו קלף מספר שמתחלק ב-{{denom}} (כמו {{number}}) כדי לפתור את האתגר ולסיים את המתקפה.',
    fractionDefenseMathReady: "כל הכבוד! פתרתם את האתגר מתמטית. לחצו 'שגר' כדי לסיים!",
    fractionDefenseRollReady: "אסטרטגיה מעולה! גלגלתם את האתגר לשחקן הבא. לחצו 'שגר' כדי לסיים!",
    fractionPileA11y: 'הערימה המרכזית',
    fractionShowcase: 'הכירו את קלפי השבר! חצי (½), שליש (⅓), רבע (¼) וחמישית (⅕). זרקו אותם על קלפי המספר שבערימה כדי להיפטר מהם ולהתקיף!',
    // Defense — dynamic, hand-derived action buttons.
    fractionDefenseTitle: 'אותגרת! הונח עליך קלף שבר.',
    fractionDefensePick: 'בחר קלף להגנה מהמניפה.',
    fractionPlaceNumber: 'שבץ {{value}}',
    fractionUseCard: 'גלגל עם {{fraction}}',
    fractionChooseDefense: 'בחר קלף להגנה',
    // ── Active 2-step intro practice (build the equation from scratch) ──
    chooseDice: 'בחר קוביות',
    placePlusOp: 'הצב את סימן החיבור',
    placeMinusOp: 'הצב את סימן החיסור',
    practicePlusSub1: 'הביטו בקלף 6 שבמניפה שלכם. מצאו קוביות שביחד שוות בדיוק 6! לחצו על קוביית ה-2 כדי להתחיל.',
    practicePlusSub2: 'מעולה! עכשיו לחצו על סימן החיבור (+) כדי לחבר אליה קובייה נוספת.',
    practicePlusSub3: 'בול! עכשיו לחצו על קוביית ה-4 כדי להשלים את הסכום ל-6.',
    practicePlusSub4: 'התרגיל מושלם! עכשיו לחצו על קלף 6 במניפה שלכם כדי להשלים אותו.',
    practiceMinusSub1: 'עכשיו נתרגל חיסור! הביטו בקלף 3 שבמניפה. מצאו קוביות שההפרש ביניהן הוא בדיוק 3. לחצו על קוביית ה-5 כדי להתחיל.',
    practiceMinusSub2: 'מצוין! עכשיו לחצו על סימן החיסור (-) כדי להפחית קובייה.',
    practiceMinusSub3: 'כל הכבוד! עכשיו לחצו על קוביית ה-2 כדי להשלים את התרגיל.',
    practiceMinusSub4: 'התרגיל מושלם! עכשיו לחצו על קלף 3 במניפה שלכם כדי להשלים אותו.',
    practiceLaunchHint: "מעולה! לחצו על 'בדוק ✓' כדי להעיף את הקלף!",
    // ── Gameplay: actionable sign-placement prompts (no explanatory text) ──
    signSelectPrompt: 'בחר סימן מהמניפה כדי להשלים את התרגיל.',
    signSelectPlace: 'לחץ על המיקום המהבהב כדי להציב את הסימן.',
    // ── Discard helper (green→red "how to get rid of a card") ──
    discardHelperOpen: 'איך להיפטר מקלף?',
    discardHelperOpenWarn: 'איך להיפטר מקלף?\nזה יעלה קלף',
    discardHelperPenaltyWarning: 'זהירות: שימוש נוסף יגרור שליפת קלף קנס!',
    discardHelperTapHint: 'לחצו על מיני קלף כדי לראות את התרגיל',
    swapBracketsPlaceholder: 'שינוי מיקום הסוגריים',
    discardHelperA11y: 'איך להיפטר מקלף — הצג תוצאות אפשריות',
    discardHelperTileTitle: 'גלגל הצלה',
    discardHelperTileDesc: 'איך להיפטר מקלף כשאין לכם מהלך ברור.',
    discardHelperIntroBody: 'לא מוצאים תרגיל מתאים לקלפים שלכם? הכפתור הירוק ייתן את התשובה!',
    discardHelperMiniCardHelp: 'הכפתור הירוק מצא עבורכם 3 פתרונות שונים!\nלחצו על מיני-קלף כדי לחשוף את המשוואה שלו על הלוח.',
    discardHelperShowcaseStep2: 'הכפתור הירוק סרק את המניפה ומצא 3 פתרונות!\nכל מיני-קלף מסתיר תרגיל שמתאים בדיוק לקלפים שלכם.',
    discardHelperShowcaseStep3: 'בכל מיני-קלף מסתתר תרגיל אחר - אתם יכולים ללחוץ על כולם,\nלבדוק את המשוואות ולבחור את התרגיל הכי טוב עבורכם.',
    // ── "איך משתפרים?" — שלב ההדרכה האחרון (אחרי מיוחדים) ──
    improveTitle: 'סוד הניצחון',
    improveDesc: 'גלה אילו תרגילים אפשר לבנות מהקוביות כדי להיפטר מקלף.',
    // ── Optional bonus practice (× / ÷) + the mandatory-reward choice screen ──
    practiceMulSub1: 'הגיע הזמן לכפל! הביטו בקלף 6 שבמניפה. מצאו קוביות שמכפלתן 6. לחצו על קוביית ה-3 כדי להתחיל.',
    practiceMulSub2: 'מצוין! עכשיו לחצו על סימן הכפל (×) כדי להכפיל.',
    practiceMulSub3: 'יופי! עכשיו לחצו על קוביית ה-2 כדי להשלים את המכפלה ל-6.',
    practiceMulSub4: 'התרגיל מושלם! עכשיו לחצו על קלף 6 במניפה שלכם כדי להשלים אותו.',
    practiceDivSub1: 'ולסיום — חילוק! הביטו בקלף 3 שבמניפה. מצאו קוביות שמנתן 3. לחצו על קוביית ה-6 כדי להתחיל.',
    practiceDivSub2: 'מצוין! עכשיו לחצו על סימן החילוק (÷) כדי לחלק.',
    practiceDivSub3: 'כל הכבוד! עכשיו לחצו על קוביית ה-2 כדי להשלים את המנה ל-3.',
    practiceDivSub4: 'התרגיל מושלם! עכשיו לחצו על קלף 3 במניפה שלכם כדי להשלים אותו.',
    placeMulOp: 'הצב את סימן הכפל',
    placeDivOp: 'הצב את סימן החילוק',
    rewardChoiceTitle: 'כל הכבוד! 🪙',
    rewardChoiceSub: 'סיימתם את שלב החובה וקיבלתם את המטבעות! רוצים לתרגל גם כפל וחילוק?',
    rewardChoiceFinish: 'הבנתי, סיימנו!',
    rewardChoiceContinue: 'תרגול נוסף: כפל וחילוק',
  },
  en: {
    entryLabel: '🪙 The Gold Room',
    entryA11y: 'Open the Gold Room',
    roomName: 'The Gold Room',
    roomTitle: 'The Gold Room 🪙',
    chooseTask: 'Choose a training task · Completed {{doneCount}}/{{totalUnlocked}}',
    exit: 'Exit',
    backToRoom: 'Back to the Gold Room',
    skip: 'Skip ›',
    back: '‹ Back',
    backPlain: 'Back',
    backShort: '‹ Back',
    continue: 'Continue ›',
    gotIt: "Got it, let's move forward!",
    close: 'Close',
    start: 'Start ›',
    completed: 'Completed ✓',
    comingSoon: '🔒 Coming Soon',
    collected: 'Collected ✓',
    collect: 'Collect ›',
    finishLearning: '🔒 Finish Learning',
    collectedA11y: ' (Collected)',
    collectAvailableA11y: ' (Available to collect)',
    finishLearningA11y: ' (Locked — finish learning)',
    completedA11y: ' (Completed)',
    comingSoonA11y: ' (Coming soon..)',
    basicsTitle: 'The Basics',
    basicsDesc: 'The Deck, the Fan, and the Dice — in under a minute.',
    basicsPracticeTitle: 'The Basics and Practice',
    basicsPracticeDesc: 'Learn the screen, then continue straight into your first equation.',
    practiceTitle: 'Practice',
    practiceDesc: 'Choose a card, roll dice, and build an equation.',
    specialsTitle: 'Specials',
    specialsSteps: ['The + / - sign cards', 'The Salinda wild operator', 'The Wild number card', 'Finale and victory'],
    fractionsTitle: 'Fractions',
    fractionsDesc: 'How to play with fraction cards.',
    salindasTitle: 'Salindas',
    salindasDesc: 'A wildcard operator that carries every sign.',
    coinsTitle: 'Coins',
    coinsDesc: 'Finish learning and collect the reward.',
    welcomeTitle: 'Welcome! 🪙',
    welcomeBody: "Let's quickly get to know the screen — only three parts, and then we play.",
    deckTag: 'The Deck',
    deckTitle: 'The Deck 🂠',
    deckBody: 'The Deck — the card bank, right up here in the corner.',
    fanBody: 'The Fan. This is your hand of cards. Swipe sideways to cycle through the cards and choose the one that fits the equation.',
    victoryBody: "Victory. Start with 7 cards, and win when left with 2 cards or less. With each correct equation, you'll get rid of a card and get closer to victory.",
    diceBody: "Each turn, three dice will be rolled on the board and determine the fate of the round. From the numbers that come up, you'll build the equations to get rid of your fan cards.",
    rewardTitle: 'Well done!',
    rewardSub: 'You received {{reward}} coins for completing the training.',
    awesome: 'Awesome!',
    errorTitle: 'Oops…',
    errorSub: "We couldn't credit your reward right now. Please try again in a moment.",
    tryAgain: 'Try Again',
    add: 'Add {{value}}',
    addDie: 'Add die {{value}}',
    removeDie: 'Remove die {{value}}',
    check: 'Check',
    checkMark: 'Check ✓',
    chooseCards: 'Choose Cards',
    launch: 'Launch',
    finish: 'Finish',
    placePlusCard: 'Place a plus card in the sign slot',
    placeSignCard: 'Place a plus card in the sign slot',
    changeAction: 'Change action',
    checkEquation: 'Check the equation',
    practicePlus: "Look at the dice and the fan. We've put together an addition (+) equation that equals exactly 6. Now, find and tap card 6 in your fan to select it!",
    practiceMinus: "Great job! Now the challenge grows and we move to subtraction (-). We've put together a subtraction equation (5 - 2) that equals exactly 3. Find and tap card 3 in your fan!",
    firstCardLaunch: "Awesome! Now tap the 'Launch' button to fly your first card!",
    cardLaunch: "Excellent! Tap the 'Launch' button to fly the card!",
    twoDiceHint: 'Two dice are enough — a third die is optional, not mandatory.',
    successSub: 'You built an equation from the dice and got rid of the matching card ✓',
    salindaIntro: 'Missing the right sign? Meet the Salinda Card, the strongest card in the game, carrying all operators at once.',
    salindaSelected: "Brilliant! The Salinda Card charged with the right sign and completed the equation. Tap the 'Launch' button to win the Gold Room!",
    salindaPractice: 'Tap the Salinda Card in your fan, choose a sign, and place it into the equation.',
    salindaOperatorIntro: 'Missing the right sign? Meet the Salinda Card! The strongest card in the game, carrying all operators at once. Tap it in your fan!',
    salindaSelectorTitle: 'Choose a sign',
    salindaSelectorBody: 'Choose the sign you need to solve the equation (5 minus 2 equals 3)!',
    chooseOperatorA11y: 'Choose operator {{op}}',
    salindaMinusLoaded: 'Great! Now tap the empty sign slot in the equation to place the Salinda Card as minus!',
    salindaOperatorReady: "The equation is perfect! Tap card 3 in the fan and then 'Launch' to win the Gold Room!",
    operatorReady: "The equation is perfect! Tap card 7 in the fan and then 'Launch' to fly it!",
    minusSlotReady: 'Excellent! Now tap the empty slot in the equation to place the plus card there.',
    minusIntro: "Now it's your turn with addition! Here is an equation of 5 and 2 that equals 7, but the plus sign is missing. Tap the plus (+) card in the fan!",
    buildTarget: 'Build an equation that reaches the target',
    salindaTurn: "Salinda Card's turn",
    salindaActive: '👑 Salinda Card Active',
    // ── Specials sequence — opening showcase + three continuous on-board substeps ──
    signCardsShowcase: 'Meet the sign cards: plus (+), minus (−), times (×) and divide (÷). Place them in the equation to get rid of them!',
    specialsLetsPractice: "Let's practice!",
    signCardsIntro: 'Meet the sign cards + / -. Place them in the equation to get rid of them.',
    salindaSeqIntro: 'Meet the Salinda Card. It carries every sign at once! Choose a sign, place it in the equation, and get rid of the card.',
    salindaSeqSelectorBody: 'Choose the sign that solves 5 - 2 = 3.',
    salindaSeqReady: "Brilliant! Tap card 3 in the fan and then 'Launch' to fly it!",
    wildIntro: 'Wild card practice: tap the Wild Card in your fan to complete the missing result in the equation.',
    wildReady: "The card became 8 and completed the equation. Tap the 'Launch' button to win!",
    // ── Fraction cards training — attack (part A) + defense (part B) ──
    fractionAttackIntro: 'Meet the fraction cards! Throw the {{fraction}} fraction card onto the {{number}} in the pile to get rid of it and attack the next player!',
    fractionDefenseIntro: "You've been challenged! First solution: place a number card divisible by {{denom}} (like {{number}}) to solve the challenge and end the attack.",
    fractionDefenseMathReady: "Well done! You solved the challenge mathematically. Tap 'Launch' to finish!",
    fractionDefenseRollReady: "Great strategy! You rolled the challenge over to the next player. Tap 'Launch' to finish!",
    fractionPileA11y: 'The center pile',
    fractionShowcase: 'Meet the fraction cards! Half (½), third (⅓), quarter (¼) and fifth (⅕). Throw them onto number cards in the pile to get rid of them and attack!',
    // Defense — dynamic, hand-derived action buttons.
    fractionDefenseTitle: "You've been challenged! A fraction card was placed on you.",
    fractionDefensePick: 'Choose a defense card from your hand.',
    fractionPlaceNumber: 'Place {{value}}',
    fractionUseCard: 'Roll with {{fraction}}',
    fractionChooseDefense: 'Choose a defense card',
    // ── Active 2-step intro practice (build the equation from scratch) ──
    chooseDice: 'Choose dice',
    placePlusOp: 'Place the plus sign',
    placeMinusOp: 'Place the minus sign',
    practicePlusSub1: 'Look at card 6 in your fan. Find dice that together equal exactly 6! Tap die 2 to begin.',
    practicePlusSub2: 'Great! Now tap the plus (+) sign to add another die to it.',
    practicePlusSub3: 'Spot on! Now tap die 4 to complete the sum to 6.',
    practicePlusSub4: 'The equation is perfect! Now tap card 6 in your fan to complete it.',
    practiceMinusSub1: "Now let's practice subtraction! Look at card 3 in your fan. Find dice whose difference is exactly 3. Tap die 5 to begin.",
    practiceMinusSub2: 'Excellent! Now tap the minus (−) sign to subtract a die.',
    practiceMinusSub3: 'Well done! Now tap die 2 to complete the exercise.',
    practiceMinusSub4: 'The equation is perfect! Now tap card 3 in your fan to complete it.',
    practiceLaunchHint: "Great! Tap 'Check ✓' to fly the card!",
    // ── Gameplay: actionable sign-placement prompts (no explanatory text) ──
    signSelectPrompt: 'Choose a sign from your fan to complete the exercise.',
    signSelectPlace: 'Tap the flashing spot to place the sign.',
    // ── Discard helper (green→red "how to get rid of a card") ──
    discardHelperOpen: 'How to\ndiscard a card?',
    discardHelperOpenWarn: 'Discard a card?\nPenalty next',
    discardHelperPenaltyWarning: 'Careful: another use draws a penalty card!',
    discardHelperTapHint: 'Tap a mini-card to see the equation',
    swapBracketsPlaceholder: 'Move the brackets',
    discardHelperA11y: 'How to discard a card — show possible results',
    discardHelperTileTitle: 'Lifeline',
    discardHelperTileDesc: "How to discard a card when no move is obvious.",
    discardHelperIntroBody: 'Stuck and could not find a matching equation? There is a solution!',
    discardHelperMiniCardHelp: 'The green button found 3 different solutions for you!\nTap a mini-card to reveal its equation on the board.',
    discardHelperShowcaseStep2: 'The green button scanned your fan and found 3 solutions!\nEach mini-card hides an equation that matches your cards.',
    discardHelperShowcaseStep3: 'Each mini-card hides a different equation - you can tap them all,\ncheck the equations, and choose the best one for you.',
    // ── "How to improve?" — the final tutorial stage (after Specials) ──
    improveTitle: 'The Secret of Victory',
    improveDesc: 'Discover which equations you can build from the dice to discard a card.',
    // ── Optional bonus practice (× / ÷) + the mandatory-reward choice screen ──
    practiceMulSub1: 'Time for multiplication! Look at card 6 in your fan. Find dice whose product is 6. Tap die 3 to begin.',
    practiceMulSub2: 'Great! Now tap the times (×) sign to multiply.',
    practiceMulSub3: 'Nice! Now tap die 2 to complete the product to 6.',
    practiceMulSub4: 'The equation is perfect! Now tap card 6 in your fan to complete it.',
    practiceDivSub1: 'And finally — division! Look at card 3 in your fan. Find dice whose quotient is 3. Tap die 6 to begin.',
    practiceDivSub2: 'Great! Now tap the divide (÷) sign to divide.',
    practiceDivSub3: 'Well done! Now tap die 2 to complete the quotient to 3.',
    practiceDivSub4: 'The equation is perfect! Now tap card 3 in your fan to complete it.',
    placeMulOp: 'Place the times sign',
    placeDivOp: 'Place the divide sign',
    rewardChoiceTitle: 'Well done! 🪙',
    rewardChoiceSub: 'You finished the required stage and earned your coins! Want to also practice multiplication and division?',
    rewardChoiceFinish: 'Got it, all done!',
    rewardChoiceContinue: 'Bonus practice: × and ÷',
  },
} as const;

export type GoldRoomCopy = typeof GOLD_ROOM_COPY.he | typeof GOLD_ROOM_COPY.en;

export function goldRoomCopyForLocale(locale: AppLocale): GoldRoomCopy {
  return GOLD_ROOM_COPY[locale];
}

export function interpolateCopy(template: string, params: Record<string, string | number>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => String(params[key] ?? ''));
}

export function useGoldRoomCopy(): GoldRoomCopy {
  const locale = useLocaleOptional()?.locale ?? deviceDefaultLocale();
  return goldRoomCopyForLocale(locale);
}
