import type { AppLocale } from '../../shared/i18n';
import { deviceDefaultLocale, useLocaleOptional } from '../i18n/LocaleContext';

export const GOLD_ROOM_COPY = {
  he: {
    entryLabel: '🪙 חדר הזהב',
    entryA11y: 'פתח את חדר הזהב',
    roomName: 'חדר הזהב',
    roomTitle: 'חדר הזהב 🪙',
    chooseTask: 'בחר משימת אימון · הושלמו {{doneCount}}/{{totalUnlocked}}',
    exit: 'יציאה',
    backToRoom: 'חזרה לחדר הזהב',
    skip: 'דלג ›',
    back: '‹ חזור',
    backPlain: 'חזור',
    backShort: '‹ חזרה',
    continue: 'המשך ›',
    gotIt: 'הבנתי, בוא נתקדם!',
    close: 'סגור',
    start: 'התחל ›',
    completed: 'הושלם ✓',
    comingSoon: '🔒 בקרוב',
    collected: 'נאסף ✓',
    collect: 'אסוף ›',
    finishLearning: '🔒 סיים ללמוד',
    collectedA11y: ' (נאסף)',
    collectAvailableA11y: ' (זמין לאיסוף)',
    finishLearningA11y: ' (נעול — סיים את הלמידה)',
    completedA11y: ' (הושלם)',
    comingSoonA11y: ' (בקרוב)',
    basicsTitle: 'היסודות',
    basicsDesc: 'הערימה, המניפה והקוביות — תוך דקה.',
    practiceTitle: 'תרגול',
    practiceDesc: 'בחר קלף, הטל קוביות, ובנה משוואה.',
    specialsTitle: 'מיוחדים',
    specialsSteps: ['קלפי הסימן + / -', 'קלף סלינדה — אופרטור פראי', 'קלף הפרא — כל מספר', 'פינאלה וניצחון'],
    fractionsTitle: 'שברים',
    fractionsDesc: 'איך משחקים עם קלפי שברים.',
    salindasTitle: 'קלפי סלינדה',
    salindasDesc: 'אופרטור פראי שמכיל את כל הסימנים.',
    coinsTitle: 'מטבעות',
    coinsDesc: 'סיים את הלמידה ואסוף את המענק.',
    welcomeTitle: 'ברוך הבא! 🪙',
    welcomeBody: 'נכיר במהירות את המסך — שלושה חלקים בלבד, ואז יוצאים לשחק.',
    deckTag: 'הערימה',
    deckTitle: 'הערימה 🂠',
    deckBody: 'הערימה — בנק הקלפים, כאן למעלה בפינה.',
    fanBody: 'המניפה. זאת מניפת הקלפים שלך. החליקו לצדדים כדי לעבור בין הקלפים ולבחור את הקלף שמתאים לתרגיל.',
    victoryBody: 'הניצחון. מתחילים עם 7 קלפים, ומנצחים כשנשארים עם 2 קלפים או פחות. בכל תרגיל נכון תיפטרו מקלף ותתקרבו לניצחון.',
    diceBody: 'בכל תור, שלוש קוביות שיוטלו על הלוח ויקבעו את גורל הסיבוב. מהמספרים שיעלו תרכיבו את התרגילים שבעזרתם תיפטרו מקלפי המניפה שלכם.',
    rewardTitle: 'כל הכבוד!',
    rewardSub: 'קיבלת {{reward}} מטבעות על סיום הלמידה.',
    awesome: 'מעולה!',
    errorTitle: 'אופס…',
    errorSub: 'לא הצלחנו לזכות אותך כרגע. נסה שוב בעוד רגע.',
    tryAgain: 'נסה שוב',
    add: 'הוסף {{value}}',
    addDie: 'הוסף קובייה {{value}}',
    removeDie: 'הסר קובייה {{value}}',
    check: 'בדוק',
    checkMark: 'בדוק ✓',
    chooseCards: 'בחר קלפים',
    launch: 'שגר',
    finish: 'סיום',
    placePlusCard: 'מקם קלף פלוס בחריץ הסימן',
    placeSignCard: 'מקם קלף סימן בחריץ הריק',
    changeAction: 'החלף פעולה',
    checkEquation: 'בדוק את המשוואה',
    practicePlus: 'הביטו בקוביות ובמניפה. הרכבנו עבורכם תרגיל חיבור (+) שמגיע בדיוק ל-6. עכשיו, מצאו ולחצו על קלף 6 במניפה שלכם כדי לבחור אותו!',
    practiceMinus: 'עבודה מעולה! עכשיו האתגר גדל ועוברים לחיסור (-). הרכבנו עבורכם תרגיל חיסור (5 - 2) שמגיע בדיוק ל-3. מצאו ולחצו על קלף 3 במניפה שלכם!',
    firstCardLaunch: "מעולה! עכשיו לחצו על כפתור 'שגר' כדי להעיף את הקלף הראשון!",
    cardLaunch: "מצוין! לחצו על כפתור 'שגר' כדי להעיף את הקלף!",
    twoDiceHint: 'שתי קוביות מספיקות — קובייה שלישית היא רשות, לא חובה.',
    successSub: 'בנית תרגיל מהקוביות ונפטרת מהקלף המתאים ✓',
    salindaIntro: 'נתקעתם בלי הסימן המתאים? הכירו את קלף סלינדה! הקלף החזק ביותר במשחק שמכיל את כל הסימנים יחד.',
    salindaSelected: "מבריק! קלף סלינדה נטען בסימן הנכון והשלים את התרגיל. לחצו על כפתור 'שגר' כדי לנצח את חדר הזהב!",
    salindaPractice: 'בואו ננסה! לחצו על קלף סלינדה במניפה, בחרו סימן, והשחילו אותו למשוואה.',
    salindaOperatorIntro: 'נתקעתם בלי הסימן המתאים? הכירו את קלף סלינדה! הקלף החזק ביותר במשחק שמכיל את כל הסימנים יחד. לחצו עליו במניפה!',
    salindaSelectorTitle: 'בחרו סימן',
    salindaSelectorBody: 'בחרו את הסימן שאתם צריכים כדי לפתור את התרגיל (5 ו-2 ששווים ל-3)!',
    chooseOperatorA11y: 'בחר סימן {{op}}',
    salindaMinusLoaded: 'מעולה! עכשיו לחצו על חריץ הסימן הריק במשוואה כדי למקם את קלף סלינדה כמינוס!',
    salindaOperatorReady: "התרגיל מושלם! לחצו על קלף 3 במניפה ואז על 'שגר' כדי לנצח את חדר הזהב!",
    operatorReady: "התרגיל מושלם! לחצו על קלף 3 במניפה ואז על 'שגר' כדי להעיף אותו!",
    minusSlotReady: 'מצוין! עכשיו לחצו על חריץ הסימן הריק שבמשוואה למעלה.',
    minusIntro: 'כאן מחכה תרגיל של 5 ו-2 ששווה ל-3. לחצו על קלף המינוס (-) במניפה!',
    buildTarget: 'בנו משוואה שמגיעה ליעד',
    salindaTurn: 'תורו של קלף סלינדה',
    salindaActive: '👑 קלף סלינדה פעיל',
    // ── Specials sequence — three continuous on-board substeps ──
    signCardsIntro: 'הכירו את קלפי הסימן + / -. הציבו אותם בתרגיל וכך תיפטרו מהם',
    salindaSeqIntro: 'הכירו את קלף סלינדה. הוא מכיל את כל הסימנים יחד! בחרו סימן, הציבו בתרגיל וכך תיפטרו מהקלף.',
    salindaSeqSelectorBody: 'בחרו את הסימן שאתם צריכים כדי לפתור את התרגיל!',
    salindaSeqReady: "מבריק! לחצו על קלף 12 במניפה ואז על 'שגר' כדי להעיף אותו!",
    wildIntro: 'הכירו את קלף הפרא! הוא יכול להפוך לכל מספר שחסר לכם במניפה כדי להשלים את המשוואה.',
    wildReady: "הקלף הפך ל-8 והשלים את התרגיל. לחצו על כפתור 'שגר' כדי לנצח!",
  },
  en: {
    entryLabel: '🪙 The Gold Room',
    entryA11y: 'Open the Gold Room',
    roomName: 'The Gold Room',
    roomTitle: 'The Gold Room 🪙',
    chooseTask: 'Choose a training task · Completed {{doneCount}}/{{totalUnlocked}}',
    exit: 'Exit',
    backToRoom: 'Back to the Gold Room',
    skip: 'Skip ›',
    back: '‹ Back',
    backPlain: 'Back',
    backShort: '‹ Back',
    continue: 'Continue ›',
    gotIt: "Got it, let's move forward!",
    close: 'Close',
    start: 'Start ›',
    completed: 'Completed ✓',
    comingSoon: '🔒 Coming Soon',
    collected: 'Collected ✓',
    collect: 'Collect ›',
    finishLearning: '🔒 Finish Learning',
    collectedA11y: ' (Collected)',
    collectAvailableA11y: ' (Available to collect)',
    finishLearningA11y: ' (Locked — finish learning)',
    completedA11y: ' (Completed)',
    comingSoonA11y: ' (Coming soon..)',
    basicsTitle: 'The Basics',
    basicsDesc: 'The Deck, the Fan, and the Dice — in under a minute.',
    practiceTitle: 'Practice',
    practiceDesc: 'Choose a card, roll dice, and build an equation.',
    specialsTitle: 'Specials',
    specialsSteps: ['The + / - sign cards', 'The Salinda wild operator', 'The Wild number card', 'Finale and victory'],
    fractionsTitle: 'Fractions',
    fractionsDesc: 'How to play with fraction cards.',
    salindasTitle: 'Salindas',
    salindasDesc: 'A wildcard operator that carries every sign.',
    coinsTitle: 'Coins',
    coinsDesc: 'Finish learning and collect the reward.',
    welcomeTitle: 'Welcome! 🪙',
    welcomeBody: "Let's quickly get to know the screen — only three parts, and then we play.",
    deckTag: 'The Deck',
    deckTitle: 'The Deck 🂠',
    deckBody: 'The Deck — the card bank, right up here in the corner.',
    fanBody: 'The Fan. This is your hand of cards. Swipe sideways to cycle through the cards and choose the one that fits the equation.',
    victoryBody: "Victory. Start with 7 cards, and win when left with 2 cards or less. With each correct equation, you'll get rid of a card and get closer to victory.",
    diceBody: "Each turn, three dice will be rolled on the board and determine the fate of the round. From the numbers that come up, you'll build the equations to get rid of your fan cards.",
    rewardTitle: 'Well done!',
    rewardSub: 'You received {{reward}} coins for completing the training.',
    awesome: 'Awesome!',
    errorTitle: 'Oops…',
    errorSub: "We couldn't credit your reward right now. Please try again in a moment.",
    tryAgain: 'Try Again',
    add: 'Add {{value}}',
    addDie: 'Add die {{value}}',
    removeDie: 'Remove die {{value}}',
    check: 'Check',
    checkMark: 'Check ✓',
    chooseCards: 'Choose Cards',
    launch: 'Launch',
    finish: 'Finish',
    placePlusCard: 'Place a plus card in the sign slot',
    placeSignCard: 'Place a plus card in the sign slot',
    changeAction: 'Change action',
    checkEquation: 'Check the equation',
    practicePlus: "Look at the dice and the fan. We've put together an addition (+) equation that equals exactly 6. Now, find and tap card 6 in your fan to select it!",
    practiceMinus: "Great job! Now the challenge grows and we move to subtraction (-). We've put together a subtraction equation (5 - 2) that equals exactly 3. Find and tap card 3 in your fan!",
    firstCardLaunch: "Awesome! Now tap the 'Launch' button to fly your first card!",
    cardLaunch: "Excellent! Tap the 'Launch' button to fly the card!",
    twoDiceHint: 'Two dice are enough — a third die is optional, not mandatory.',
    successSub: 'You built an equation from the dice and got rid of the matching card ✓',
    salindaIntro: 'Missing the right sign? Meet the Salinda Card, the strongest card in the game, carrying all operators at once.',
    salindaSelected: "Brilliant! The Salinda Card charged with the right sign and completed the equation. Tap the 'Launch' button to win the Gold Room!",
    salindaPractice: 'Tap the Salinda Card in your fan, choose a sign, and place it into the equation.',
    salindaOperatorIntro: 'Missing the right sign? Meet the Salinda Card! The strongest card in the game, carrying all operators at once. Tap it in your fan!',
    salindaSelectorTitle: 'Choose a sign',
    salindaSelectorBody: 'Choose the sign you need to solve the equation (5 and 2 equal 3)!',
    chooseOperatorA11y: 'Choose operator {{op}}',
    salindaMinusLoaded: 'Great! Now tap the empty sign slot in the equation to place the Salinda Card as minus!',
    salindaOperatorReady: "The equation is perfect! Tap card 3 in the fan and then 'Launch' to win the Gold Room!",
    operatorReady: "The equation is perfect! Tap card 3 in the fan and then 'Launch' to fly it!",
    minusSlotReady: 'Excellent! Now tap the empty slot in the equation to place the minus card there.',
    minusIntro: "Now it's your turn with subtraction! Here is an equation of 5 and 2 that equals 3, but the subtraction sign is missing. Tap the minus (-) card in the fan!",
    buildTarget: 'Build an equation that reaches the target',
    salindaTurn: "Salinda Card's turn",
    salindaActive: '👑 Salinda Card Active',
    // ── Specials sequence — three continuous on-board substeps ──
    signCardsIntro: 'Meet the sign cards + / -. Place them in the equation to get rid of them.',
    salindaSeqIntro: 'Meet the Salinda Card. It carries every sign at once! Choose a sign, place it in the equation, and get rid of the card.',
    salindaSeqSelectorBody: 'Choose the sign you need to solve the equation!',
    salindaSeqReady: "Brilliant! Tap card 12 in the fan and then 'Launch' to fly it!",
    wildIntro: 'Meet the Wild Card! It can become any number you are missing in your fan to complete the equation.',
    wildReady: "The card became 8 and completed the equation. Tap the 'Launch' button to win!",
  },
} as const;

export type GoldRoomCopy = typeof GOLD_ROOM_COPY.he | typeof GOLD_ROOM_COPY.en;

export function goldRoomCopyForLocale(locale: AppLocale): GoldRoomCopy {
  return GOLD_ROOM_COPY[locale];
}

export function interpolateCopy(template: string, params: Record<string, string | number>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => String(params[key] ?? ''));
}

export function useGoldRoomCopy(): GoldRoomCopy {
  const locale = useLocaleOptional()?.locale ?? deviceDefaultLocale();
  return goldRoomCopyForLocale(locale);
}
